In [100]:
%matplotlib inline
import os
from IPython.display import Image
from IPython.display import display
import numpy as np
import pandas as pd
from scipy import interp
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import auc, confusion_matrix,  f1_score, precision_score, recall_score, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from cycler import cycler
import matplotlib
matplotlib.rcParams.update({'font.size': 22})
plt = matplotlib.pyplot

### Create team

In [70]:
df_team = pd.read_csv("team\\team_italy.csv")


In [71]:
df_team

Rk          Squad  MP   W   D   L  GF  GA  GD  Pts    xG   xGA   xGD  \
0    1          Inter  38  28   7   3  89  35  54   91  74.8  38.6  36.2   
1    2          Milan  38  24   7   7  74  41  33   79  71.2  45.7  25.5   
2    3       Atalanta  38  23   9   6  90  47  43   78  77.1  42.3  34.8   
3    4       Juventus  38  23   9   6  77  38  39   78  74.2  38.2  36.0   
4    5         Napoli  38  24   5   9  86  41  45   77  67.7  41.6  26.1   
5    6          Lazio  38  21   5  12  61  55   6   68  59.8  47.8  12.0   
6    7           Roma  38  18   8  12  68  58  10   62  68.9  51.4  17.5   
7    8       Sassuolo  38  17  11  10  64  56   8   62  59.2  54.9   4.3   
8    9      Sampdoria  38  15   7  16  52  54  -2   52  46.2  56.9 -10.7   
9   10  Hellas Verona  38  11  12  15  46  48  -2   45  43.5  50.3  -6.8   
10  11          Genoa  38  10  12  16  47  58 -11   42  37.8  54.5 -16.8   
11  12        Bologna  38  10  11  17  51  65 -14   41  53.4  64.7 -11.2   
12  13     Fiorentina  38   9  13  16  47  59 -12   40  45.2  55.1  -9.9   
13  14        Udinese  38  10  10  18  42  58 -16   40  42.9  52.1  -9.2   
14  15         Spezia  38   9  12  17  52  72 -20   39  46.7  69.3 -22.6   
15  16       Cagliari  38   9  10  19  43  59 -16   37  45.5  63.1 -17.6   
16  17         Torino  38   7  16  15  50  69 -19   37  50.2  58.8  -8.6   
17  18      Benevento  38   7  12  19  40  75 -35   33  41.6  66.1 -24.5   
18  19        Crotone  38   6   5  27  45  92 -47   23  38.5  71.6 -33.1   
19  20          Parma  38   3  11  24  39  83 -44   20  40.0  61.4 -21.4   

    xGD/90  Attendance           Top Team Scorer            Goalkeeper  \
0     0.95         158        Romelu Lukaku - 24      Samir Handanović   
1     0.67         105   Zlatan Ibrahimović - 15  Gianluigi Donnarumma   
2     0.92         105          Luis Muriel - 22     Pierluigi Gollini   
3     0.95         105    Cristiano Ronaldo - 29     Wojciech Szczęsny   
4     0.69         105      Lorenzo Insigne - 19            Alex Meret   
5     0.32         158        Ciro Immobile - 20            Pepe Reina   
6     0.46         105   Henrikh Mkhitaryan - 13             Pau López   
7     0.11         134     Domenico Berardi - 17       Andrea Consigli   
8    -0.28         105   Fabio Quagliarella - 13           Emil Audero   
9    -0.18         611         Antonín Barák - 7       Marco Silvestri   
10   -0.44          53        Mattia Destro - 11          Mattia Perin   
11   -0.30         105       Roberto Soriano - 9      Łukasz Skorupski   
12   -0.26         105       Dušan Vlahović - 21  Bartłomiej Drągowski   
13   -0.24         158       Rodrigo De Paul - 9            Juan Musso   
14   -0.59         105         M'Bala Nzola - 11         Ivan Provedel   
15   -0.46         105           João Pedro - 16        Alessio Cragno   
16   -0.23         105       Andrea Belotti - 13      Salvatore Sirigu   
17   -0.64         158     Gianluca Lapadula - 8       Lorenzo Montipò   
18   -0.87          53       Simeon Nwankwo - 20           Alex Cordaz   
19   -0.56         158  Juraj Kucka, Hernani - 7            Luigi Sepe   

                                                Notes  
0           → UEFA Champions League via league finish  
1           → UEFA Champions League via league finish  
2           → UEFA Champions League via league finish  
3           → UEFA Champions League via league finish  
4              → UEFA Europa League via league finish  
5            → UEFA Europa League via league finish 1  
6   → UEFA Europa Conference League via league finish  
7                                                 NaN  
8                                                 NaN  
9                                                 NaN  
10                                                NaN  
11                                                NaN  
12                                                NaN  
13                                                NaN  
14          

In [6]:
df_team.values[:,1]

array(['Manchester City', 'Manchester Utd', 'Liverpool', 'Chelsea',
       'Leicester City', 'West Ham', 'Tottenham', 'Arsenal',
       'Leeds United', 'Everton', 'Aston Villa', 'Newcastle Utd',
       'Wolves', 'Crystal Palace', 'Southampton', 'Brighton', 'Burnley',
       'Fulham', 'West Brom', 'Sheffield Utd'], dtype=object)

### Create player dataset

In [9]:
from glob import glob
files = glob("player_data_seriea/*.csv")

In [11]:
test=pd.read_csv(files[100])
pd.read_csv(files[100])


Unnamed: 0  Age  Squad Country        Comp LgRank  90s  Cmp  Att  Cmp%  \
0           0   23  Inter  it ITA  1. Serie A    2nd  8.0  422  515  81.9   
1           1   24  Inter  it ITA  1. Serie A    1st  6.7  351  426  82.4   

    ...    PrgDist.1  Prog.1  1/3.1  CPA  Mis  Dis  Targ  Rec  Rec%  Prog.2  
0   ...         1089      60     15    5   12   14   514  449  87.4      71  
1   ...          875      37     13    4   14    9   419  378  90.2      38  

[2 rows x 77 columns]

In [12]:
test.values[:,6]


array([8.0, 6.7], dtype=object)

In [16]:
player_n=len(files)
player_n

619

In [36]:
def one_player(df_one):
    df_num=df_one.shape[0]
    one_player=np.zeros((1, 71))
    for i in range(0,df_num):
    #print(i)
        if df_one.values[i,4]=='1. Serie A' :  # only collect the Premier Leage data
            dfxx= df_one.values[i,6:]           # collect the data after the column "LgRank"
            one_player=np.row_stack((one_player,dfxx))
        if i==df_num-1:
            player_team_one= df_one.values[i,2]
    one_player=np.delete(one_player, 0, 0)     # delete temporay row
    #one_player=np.delete(one_player, 71-15, 1) # move the column have NAN
    one_player=np.mean(one_player,axis=0)      # average the data for different seasons
    return one_player,player_team_one

In [37]:
player= np.zeros((1, 71))  #70 becuase that i delelete one NAN column
for i in range(0,player_n):   # 英超,532 players
    df_one = pd.read_csv(files[i])
    player_one,_= one_player(df_one)
    player= np.row_stack((player,player_one))
player=np.delete(player, 0, 0)     # delete temporay row

In [38]:
player.shape

(619, 71)

In [39]:
player_team= []  #70 becuase that i delelete one NAN column
for i in range(0,player_n):   # 英超,532 players
    df_one = pd.read_csv(files[i])
    _,player_team_one= one_player(df_one)
    player_team.append(player_team_one)


In [40]:
len(player_team)

619

In [44]:
player

array([[35.5, 952.0, 1102.0, ..., 627.0, 99.7, 0.0],
       [19.9, 598.0, 827.0, ..., 623.0, 82.4, 75.0],
       [12.9, 1013.0, 1073.0, ..., 948.0, 96.3, 19.0],
       ...,
       [18.9, 667.0, 784.0, ..., 707.0, 79.0, 135.0],
       [8.8, 550.5, 599.5, ..., 506.5, 98.15, 3.5],
       [18.25, 926.5, 1116.5, ..., 1110.0, 86.05, 178.0]], dtype=object)

In [45]:
X=player
X=X.astype(np.float32)

In [51]:
X.shape

(619, 71)

In [48]:
id=np.argwhere(np.isnan(X)) #尋找缺值的地方
id2=id[:,1] # 有那些feature還有missing value  # of missing:132 
id3=id[:,0] # 含missing value的player

In [52]:
X[id3].shape

(234, 71)

In [53]:
np.unique(id2)

array([ 3,  8, 11, 14, 56, 69], dtype=int64)

In [54]:
X_del_miss=np.delete(X, id3, 0)   # delete players who have missing values #備用資料集

In [55]:
X_del_miss.shape

(458, 71)

#### 補值處理  by KNN

In [65]:
from sklearn.impute import KNNImputer
#X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=11)

In [66]:
X_add_miss= imputer.fit_transform(X)


In [67]:
X_add_miss.shape

(619, 71)

In [68]:
X_add_miss[0].shape

(71,)

In [60]:
id_test=np.argwhere(np.isnan(X_add_miss))
id_test

array([], shape=(0, 2), dtype=int64)

### Create club dataset

In [61]:
def get_index(lst=None, item=''):
    return [index for (index,value) in enumerate(lst) if value == item]

In [62]:
id=get_index(player_team, 'Chelsea')

In [63]:
id

[]

In [64]:
len(player_team)

619

In [74]:
club_feature = np.zeros((1, 781))
for i in range(0,20):
    team_name=df_team.values[:,1][i]
    id_club = get_index(player_team, team_name) # 把屬於這個球隊的球員id找出來 # player_team是所有球員的對應球隊列表
    num = len(id_club)
    player_feature=np.zeros((1, 71))
    player_time_arr=np.zeros((num))
    for j in range(0,num):
        player_time_arr[j]=X_add_miss[id_club[j]][0]#
    idd =np.argsort([player_time_arr])#由小到大
    iddr = idd[::-1]
    ids = iddr[0][0:11] # select most important 11 players   #[0]
    nums = len(ids)
    for ii in range(0,nums):
        tmp=X_add_miss[ids[ii]]##<-------------------要改的是idclub
        tmp=tmp.reshape((1, 71))
        player_feature= np.column_stack((player_feature,tmp))
    #player_featurex= player_feature test
    tmpp=[i for i in range(71)]
    player_feature = np.delete(player_feature, tmpp)      # delete temporay row
    num_fe = len(player_feature)
    player_feature = player_feature.reshape((1, num_fe))
    if player_feature.shape[1]==781:
        #print("exe")
        club_feature= np.row_stack((club_feature,player_feature))
club_feature=np.delete(club_feature, 0, 0)     # delete temporay row

    

d = np.array([4,3,2,1])
d = np.pad(d,(0,5),'constant',constant_values=(0,0))
print(d)

In [75]:
club_feature.shape

(20, 781)

In [78]:
np.save("regression_X_italy.npy",club_feature)


In [94]:
df_team.values[:,1]

array(['Inter', 'Milan', 'Atalanta', 'Juventus', 'Napoli', 'Lazio',
       'Roma', 'Sassuolo', 'Sampdoria', 'Hellas Verona', 'Genoa',
       'Bologna', 'Fiorentina', 'Udinese', 'Spezia', 'Cagliari', 'Torino',
       'Benevento', 'Crotone', 'Parma'], dtype=object)

### 跳掉leeds united ,手動輸入控球率

In [95]:
Y=np.array([52.4,51.9,54.9,57.1,55.2,53.1,52.5,60.8,45.1,49.8,44.7,50.9,46.2,46.1,52.2,44.6,47.2,42.3,46.4,47.7])

In [96]:
Y.shape

(20,)

In [98]:
Y=Y.reshape((20, 1))


In [99]:
np.save("regression_Y_italy.npy",Y)
